const galleryItems = [
  // ===== ELEVATION =====
  { id:   1, title: "Elevation 01", category: "elevation", image: "assets/gallery/elevation-01.jpg" },
  { id:   2, title: "Elevation 02", category: "elevation", image: "assets/gallery/elevation-02.jpg" },
  { id:   3, title: "Elevation 03", category: "elevation", image: "assets/gallery/elevation-03.jpg" },
  { id:   4, title: "Elevation 04", category: "elevation", image: "assets/gallery/elevation-04.jpg" },
  { id:   5, title: "Elevation 05", category: "elevation", image: "assets/gallery/elevation-05.jpg" },
  { id:   6, title: "Elevation 06", category: "elevation", image: "assets/gallery/elevation-06.jpg" },
  { id:   7, title: "Elevation 07", category: "elevation", image: "assets/gallery/elevation-07.jpg" },
  { id:   8, title: "Elevation 08", category: "elevation", image: "assets/gallery/elevation-08.jpg" },
  { id:   9, title: "Elevation 09", category: "elevation", image: "assets/gallery/elevation-09.jpg" },
  { id:  10, title: "Elevation 10", category: "elevation", image: "assets/gallery/elevation-10.jpg" },
  { id:  11, title: "Elevation 11", category: "elevation", image: "assets/gallery/elevation-11.jpg" },
  { id:  12, title: "Elevation 12", category: "elevation", image: "assets/gallery/elevation-12.jpg" },
  { id:  13, title: "Elevation 13", category: "elevation", image: "assets/gallery/elevation-13.jpg" },
  { id:  14, title: "Elevation 14", category: "elevation", image: "assets/gallery/elevation-14.jpg" },
  { id:  15, title: "Elevation 15", category: "elevation", image: "assets/gallery/elevation-15.jpg" },
  { id:  16, title: "Elevation 16", category: "elevation", image: "assets/gallery/elevation-16.jpg" },
  { id:  17, title: "Elevation 17", category: "elevation", image: "assets/gallery/elevation-17.jpg" },
  { id:  18, title: "Elevation 18", category: "elevation", image: "assets/gallery/elevation-18.jpg" },
  { id:  19, title: "Elevation 19", category: "elevation", image: "assets/gallery/elevation-19.jpg" },
  { id:  20, title: "Elevation 20", category: "elevation", image: "assets/gallery/elevation-20.jpg" },
  { id:  21, title: "Elevation 21", category: "elevation", image: "assets/gallery/elevation-21.jpg" },
  { id:  22, title: "Elevation 22", category: "elevation", image: "assets/gallery/elevation-22.jpg" },
  { id:  23, title: "Elevation 23", category: "elevation", image: "assets/gallery/elevation-23.jpg" },
  { id:  24, title: "Elevation 24", category: "elevation", image: "assets/gallery/elevation-24.jpg" },
  { id:  25, title: "Elevation 25", category: "elevation", image: "assets/gallery/elevation-25.jpg" },
  { id:  26, title: "Elevation 26", category: "elevation", image: "assets/gallery/elevation-26.jpg" },
  { id:  27, title: "Elevation 27", category: "elevation", image: "assets/gallery/elevation-27.jpg" },
  { id:  28, title: "Elevation 28", category: "elevation", image: "assets/gallery/elevation-28.jpg" },
  { id:  29, title: "Elevation 29", category: "elevation", image: "assets/gallery/elevation-29.jpg" },
  { id:  30, title: "Elevation 30", category: "elevation", image: "assets/gallery/elevation-30.jpg" },
  { id:  31, title: "Elevation 31", category: "elevation", image: "assets/gallery/elevation-31.jpg" },
  { id:  32, title: "Elevation 32", category: "elevation", image: "assets/gallery/elevation-32.jpg" },

  // ===== GATES =====
  { id:  33, title: "Gates 01", category: "gates", image: "assets/gallery/gates-01.jpg" },
  { id:  34, title: "Gates 02", category: "gates", image: "assets/gallery/gates-02.jpg" },
  { id:  35, title: "Gates 03", category: "gates", image: "assets/gallery/gates-03.jpg" },
  { id:  36, title: "Gates 04", category: "gates", image: "assets/gallery/gates-04.jpg" },
  { id:  37, title: "Gates 05", category: "gates", image: "assets/gallery/gates-05.jpg" },
  { id:  38, title: "Gates 06", category: "gates", image: "assets/gallery/gates-06.jpg" },
  { id:  39, title: "Gates 07", category: "gates", image: "assets/gallery/gates-07.jpg" },
  { id:  40, title: "Gates 08", category: "gates", image: "assets/gallery/gates-08.jpg" },
  { id:  41, title: "Gates 09", category: "gates", image: "assets/gallery/gates-09.jpg" },
  { id:  42, title: "Gates 10", category: "gates", image: "assets/gallery/gates-10.jpg" },
  { id:  43, title: "Gates 11", category: "gates", image: "assets/gallery/gates-11.jpg" },
  { id:  44, title: "Gates 12", category: "gates", image: "assets/gallery/gates-12.jpg" },
  { id:  45, title: "Gates 13", category: "gates", image: "assets/gallery/gates-13.jpg" },
  { id:  46, title: "Gates 14", category: "gates", image: "assets/gallery/gates-14.jpg" },
  { id:  47, title: "Gates 15", category: "gates", image: "assets/gallery/gates-15.jpg" },
  { id:  48, title: "Gates 16", category: "gates", image: "assets/gallery/gates-16.jpg" },
  { id:  49, title: "Gates 17", category: "gates", image: "assets/gallery/gates-17.jpg" },
  { id:  50, title: "Gates 18", category: "gates", image: "assets/gallery/gates-18.jpg" },
  { id:  51, title: "Gates 19", category: "gates", image: "assets/gallery/gates-19.jpg" },
  { id:  52, title: "Gates 20", category: "gates", image: "assets/gallery/gates-20.jpg" },

  // ===== LANDSCAPE =====
  { id:  53, title: "Landscape 01", category: "landscape", image: "assets/gallery/landscape-01.jpg" },
  { id:  54, title: "Landscape 02", category: "landscape", image: "assets/gallery/landscape-02.jpg" },
  { id:  55, title: "Landscape 03", category: "landscape", image: "assets/gallery/landscape-03.jpg" },
  { id:  56, title: "Landscape 04", category: "landscape", image: "assets/gallery/landscape-04.jpg" },
  { id:  57, title: "Landscape 05", category: "landscape", image: "assets/gallery/landscape-05.jpg" },
  { id:  58, title: "Landscape 06", category: "landscape", image: "assets/gallery/landscape-06.jpg" },
  { id:  59, title: "Landscape 07", category: "landscape", image: "assets/gallery/landscape-07.jpg" },
  { id:  60, title: "Landscape 08", category: "landscape", image: "assets/gallery/landscape-08.jpg" },
  { id:  61, title: "Landscape 09", category: "landscape", image: "assets/gallery/landscape-09.jpg" },
  { id:  62, title: "Landscape 10", category: "landscape", image: "assets/gallery/landscape-10.jpg" },
  { id:  63, title: "Landscape 11", category: "landscape", image: "assets/gallery/landscape-11.jpg" },
  { id:  64, title: "Landscape 12", category: "landscape", image: "assets/gallery/landscape-12.jpg" },
  { id:  65, title: "Landscape 13", category: "landscape", image: "assets/gallery/landscape-13.jpg" },
  { id:  66, title: "Landscape 14", category: "landscape", image: "assets/gallery/landscape-14.jpg" },
  { id:  67, title: "Landscape 15", category: "landscape", image: "assets/gallery/landscape-15.jpg" },

  // ===== PERGOLA =====
  { id:  68, title: "Pergola 01", category: "pergola", image: "assets/gallery/pergola-01.jpg" },
  { id:  69, title: "Pergola 02", category: "pergola", image: "assets/gallery/pergola-02.jpg" },
  { id:  70, title: "Pergola 03", category: "pergola", image: "assets/gallery/pergola-03.jpg" },
  { id:  71, title: "Pergola 04", category: "pergola", image: "assets/gallery/pergola-04.jpg" },
  { id:  72, title: "Pergola 05", category: "pergola", image: "assets/gallery/pergola-05.jpg" },
  { id:  73, title: "Pergola 06", category: "pergola", image: "assets/gallery/pergola-06.jpg" },
  { id:  74, title: "Pergola 07", category: "pergola", image: "assets/gallery/pergola-07.jpg" },
  { id:  75, title: "Pergola 08", category: "pergola", image: "assets/gallery/pergola-08.jpg" },
  { id:  76, title: "Pergola 09", category: "pergola", image: "assets/gallery/pergola-09.jpg" },
  { id:  77, title: "Pergola 10", category: "pergola", image: "assets/gallery/pergola-10.jpg" },
  { id:  78, title: "Pergola 11", category: "pergola", image: "assets/gallery/pergola-11.jpg" },
  { id:  79, title: "Pergola 12", category: "pergola", image: "assets/gallery/pergola-12.jpg" },
  { id:  80, title: "Pergola 13", category: "pergola", image: "assets/gallery/pergola-13.jpg" },
  { id:  81, title: "Pergola 14", category: "pergola", image: "assets/gallery/pergola-14.jpg" },
  { id:  82, title: "Pergola 15", category: "pergola", image: "assets/gallery/pergola-15.jpg" },
  { id:  83, title: "Pergola 16", category: "pergola", image: "assets/gallery/pergola-16.jpg" },
  { id:  84, title: "Pergola 17", category: "pergola", image: "assets/gallery/pergola-17.jpg" },
  { id:  85, title: "Pergola 18", category: "pergola", image: "assets/gallery/pergola-18.jpg" },
  { id:  86, title: "Pergola 19", category: "pergola", image: "assets/gallery/pergola-19.jpg" },
  { id:  87, title: "Pergola 20", category: "pergola", image: "assets/gallery/pergola-20.jpg" },
  { id:  88, title: "Pergola 21", category: "pergola", image: "assets/gallery/pergola-21.jpg" },
  { id:  89, title: "Pergola 22", category: "pergola", image: "assets/gallery/pergola-22.jpg" },
  { id:  90, title: "Pergola 23", category: "pergola", image: "assets/gallery/pergola-23.jpg" },
  { id:  91, title: "Pergola 24", category: "pergola", image: "assets/gallery/pergola-24.jpg" },
  { id:  92, title: "Pergola 25", category: "pergola", image: "assets/gallery/pergola-25.jpg" },
  { id:  93, title: "Pergola 26", category: "pergola", image: "assets/gallery/pergola-26.jpg" },

  // ===== SCREENS =====
  { id:  94, title: "Screens 01", category: "screens", image: "assets/gallery/screens-01.jpg" },
  { id:  95, title: "Screens 02", category: "screens", image: "assets/gallery/screens-02.jpg" },
  { id:  96, title: "Screens 03", category: "screens", image: "assets/gallery/screens-03.jpg" },
  { id:  97, title: "Screens 04", category: "screens", image: "assets/gallery/screens-04.jpg" },
  { id:  98, title: "Screens 05", category: "screens", image: "assets/gallery/screens-05.jpg" },
  { id:  99, title: "Screens 06", category: "screens", image: "assets/gallery/screens-06.jpg" },
  { id: 100, title: "Screens 07", category: "screens", image: "assets/gallery/screens-07.jpg" },
  { id: 101, title: "Screens 08", category: "screens", image: "assets/gallery/screens-08.jpg" },
  { id: 102, title: "Screens 09", category: "screens", image: "assets/gallery/screens-09.jpg" },
  { id: 103, title: "Screens 10", category: "screens", image: "assets/gallery/screens-10.jpg" },
  { id: 104, title: "Screens 11", category: "screens", image: "assets/gallery/screens-11.jpg" },
  { id: 105, title: "Screens 12", category: "screens", image: "assets/gallery/screens-12.jpg" },
  { id: 106, title: "Screens 13", category: "screens", image: "assets/gallery/screens-13.jpg" },
  { id: 107, title: "Screens 14", category: "screens", image: "assets/gallery/screens-14.jpg" },
  { id: 108, title: "Screens 15", category: "screens", image: "assets/gallery/screens-15.jpg" },
  { id: 109, title: "Screens 16", category: "screens", image: "assets/gallery/screens-16.jpg" },
  { id: 110, title: "Screens 17", category: "screens", image: "assets/gallery/screens-17.jpg" },
  { id: 111, title: "Screens 18", category: "screens", image: "assets/gallery/screens-18.jpg" },
  { id: 112, title: "Screens 19", category: "screens", image: "assets/gallery/screens-19.jpg" },
  { id: 113, title: "Screens 20", category: "screens", image: "assets/gallery/screens-20.jpg" },
  { id: 114, title: "Screens 21", category: "screens", image: "assets/gallery/screens-21.jpg" },
  { id: 115, title: "Screens 22", category: "screens", image: "assets/gallery/screens-22.jpg" },
  { id: 116, title: "Screens 23", category: "screens", image: "assets/gallery/screens-23.jpg" },
  { id: 117, title: "Screens 24", category: "screens", image: "assets/gallery/screens-24.jpg" },
  { id: 118, title: "Screens 25", category: "screens", image: "assets/gallery/screens-25.jpg" },
  { id: 119, title: "Screens 26", category: "screens", image: "assets/gallery/screens-26.jpg" },
  { id: 120, title: "Screens 27", category: "screens", image: "assets/gallery/screens-27.jpg" },
  { id: 121, title: "Screens 28", category: "screens", image: "assets/gallery/screens-28.jpg" },
  { id: 122, title: "Screens 29", category: "screens", image: "assets/gallery/screens-29.jpg" },
  { id: 123, title: "Screens 30", category: "screens", image: "assets/gallery/screens-30.jpg" },
  { id: 124, title: "Screens 31", category: "screens", image: "assets/gallery/screens-31.jpg" },
  { id: 125, title: "Screens 32", category: "screens", image: "assets/gallery/screens-32.jpg" },
  { id: 126, title: "Screens 33", category: "screens", image: "assets/gallery/screens-33.jpg" },
  { id: 127, title: "Screens 34", category: "screens", image: "assets/gallery/screens-34.jpg" },

];

const galleryCategories = [
  { id: "all",       name: "All" },
  { id: "elevation", name: "Elevation" },
  { id: "gates", name: "Gates" },
  { id: "landscape", name: "Landscape" },
  { id: "pergola", name: "Pergola" },
  { id: "screens", name: "Screens" },
];
